# Generated by Django 6.0.4 on 2026-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('algorithm', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('feature_importances', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Прогон модели',
                'verbose_name_plural': 'Прогоны моделей',
                'ordering': ['-created_at'],
            },
        ),
    ]
