# Generated by Django 6.0.4 on 2026-05-01 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederalDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Федеральный округ',
                'verbose_name_plural': 'Федеральные округа',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_excluded', models.BooleanField(default=False, help_text='True для 6 регионов СКФО — исключаются из анализа')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regions', to='regions.federaldistrict')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PanelObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('juvenile_crime_share', models.FloatField(blank=True, help_text='Доля несовершеннолетних участников преступлений от 14–17-летнего населения, %', null=True)),
                ('gini', models.FloatField(blank=True, help_text='Коэффициент Джини', null=True)),
                ('poverty_rate', models.FloatField(blank=True, help_text='Доля населения ниже прожиточного минимума, %', null=True)),
                ('unemployment_rate', models.FloatField(blank=True, help_text='Уровень безработицы, %', null=True)),
                ('youth_unemployment', models.FloatField(blank=True, help_text='Безработица молодёжи 15–24 лет, %', null=True)),
                ('avg_income', models.FloatField(blank=True, help_text='Среднедушевой денежный доход, руб.', null=True)),
                ('real_income_index', models.FloatField(blank=True, help_text='Индекс реальных располагаемых доходов', null=True)),
                ('wage_to_subsistence', models.FloatField(blank=True, help_text='Отношение зарплаты к прожиточному минимуму', null=True)),
                ('urbanization', models.FloatField(blank=True, help_text='Доля городского населения, %', null=True)),
                ('education_coverage', models.FloatField(blank=True, help_text='Охват средним образованием, %', null=True)),
                ('alcohol_incidence', models.FloatField(blank=True, help_text='Заболеваемость алкоголизмом подростков', null=True)),
                ('population_14_17', models.IntegerField(blank=True, help_text='Численность населения 14–17 лет', null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='regions.region')),
            ],
            options={
                'verbose_name': 'Панельное наблюдение',
                'verbose_name_plural': 'Панельные наблюдения',
                'ordering': ['region', 'year'],
                'unique_together': {('region', 'year')},
            },
        ),
    ]
