# Generated by Django 6.0.4 on 2026-05-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelobservation',
            name='alcohol_incidence',
        ),
        migrations.RemoveField(
            model_name='panelobservation',
            name='education_coverage',
        ),
        migrations.RemoveField(
            model_name='panelobservation',
            name='population_14_17',
        ),
        migrations.RemoveField(
            model_name='panelobservation',
            name='youth_unemployment',
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='alcohol_per100k',
            field=models.FloatField(blank=True, help_text='Алкогольные расстройства на 100 000 чел.', null=True),
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='crime_drugs',
            field=models.FloatField(blank=True, help_text='Наркопреступления на 100 000 чел.', null=True),
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='crime_hooliganism',
            field=models.FloatField(blank=True, help_text='Хулиганство на 100 000 чел.', null=True),
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='crime_murder',
            field=models.FloatField(blank=True, help_text='Убийства на 100 000 чел.', null=True),
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='decile_coef',
            field=models.FloatField(blank=True, help_text='Децильный коэффициент, раз', null=True),
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='narco_per100k',
            field=models.FloatField(blank=True, help_text='Наркологические расстройства на 100 000 чел.', null=True),
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='pop_working_age_pct',
            field=models.FloatField(blank=True, help_text='Доля трудоспособного возраста, %', null=True),
        ),
        migrations.AddField(
            model_name='panelobservation',
            name='population_total',
            field=models.FloatField(blank=True, help_text='Численность населения, тыс. чел.', null=True),
        ),
        migrations.AlterField(
            model_name='panelobservation',
            name='avg_income',
            field=models.FloatField(blank=True, help_text='Среднедушевой доход, руб.', null=True),
        ),
        migrations.AlterField(
            model_name='panelobservation',
            name='juvenile_crime_share',
            field=models.FloatField(blank=True, help_text='Доля несовершеннолетних участников преступлений от населения 14–17 лет, %', null=True),
        ),
        migrations.AlterField(
            model_name='panelobservation',
            name='poverty_rate',
            field=models.FloatField(blank=True, help_text='Доля населения ниже прожит. минимума, %', null=True),
        ),
        migrations.AlterField(
            model_name='panelobservation',
            name='real_income_index',
            field=models.FloatField(blank=True, help_text='Индекс реальных доходов, % к пред. году', null=True),
        ),
        migrations.AlterField(
            model_name='panelobservation',
            name='unemployment_rate',
            field=models.FloatField(blank=True, help_text='Уровень безработицы (МОТ), %', null=True),
        ),
        migrations.AlterField(
            model_name='panelobservation',
            name='wage_to_subsistence',
            field=models.FloatField(blank=True, help_text='Отношение зарплаты к прожит. минимуму', null=True),
        ),
    ]
